### ISSUE TITLE
Add a setting to adjust avatar size

### ISSUE THREAD

**Issue by NoahDragon** [NoahDragon/cat-generator-avatars#9]
On my site, I usually modify the avatar size to make them looks more fit to the pages. However, directly changes to the source code will be lost after update. If we could have a setting for the plugin, that would be more convenience.

@Jon007 I don't know if this setting would affect the buddypress. If you don't have any objection, I will plan to make the change some day later.

**Comment by Jon007** [comment]
Hi, 
 - maybe the picture source file generation should be fixed size because all the source artwork is fixed size, and now we have the image generation fast because there is no resizing and conversion going on, if we add processing it might slow down again.
 - the display size can be different, this can be controlled by the theme or plugin:
  - BuddyPress under twenty-sixteen is showing the same cat picture at 50x50 and 150x150, though really 50x50 is a bit too small for some of the detail in the artwork.
  - Ultimate Member uses 100x100 and  140x140, actually it normally generates different sizes, 40, 80, 190...

**IF** the resizing is fast, the correct solution would be to generate the requested sizes, that way you generate all the sizes requested by the different themes or plugins, there is no need for a plugin setting.
So if there is currently have a cat  "70d78e.png", if the resizing code is added, we would have:
- 70d78e.png
- 70d78e-100x100.png
- 70d78e-140x140.png
and so on according to the sized requested.

Code change would be where there is eg:

```
        if (! file_exists($cachefile) ) {
            $this->build_monster($id);
        }

```
Then add:

``` 
        $sizedcachefile=$cachefile . '-' . $size . 'x' . $size;
        if (! file_exists($sizedcachefile) ) {
            $this->resize_image($cachefile, $size);
        }
```
[and write the resize_image function]
and return the resized image.

**Comment by NoahDragon** [comment]
@Jon007 Yes, you're right, if we add resize function, it may slow down the process again.

My proposed method is much simpler.  All the image size are fixed when generated, only the display size is varied by setting. The new setting will only affect the following two lines:

https://github.com/NoahDragon/cat-generator-avatars/blob/master/src/Avatar.php#L96-L97

**Comment by Jon007** [comment]
@NoahDragon No, please don't do that!

This size is passed into the function from different themes and components, it is these themes and functions which are choosing the size and maybe have their own setting for size.  
Wordpress and the components, themes, widgets, plugins use many different sizes  in different contexts, in admin users listing, user profile page (admin view and front end view), front-end user listings in widgets, comments etc 

So if you fix the display size there, it would have big impact.

So the correct solution would be change it in the theme, add appropriate filter etc.
Which screen is causing a problem for you with display size currently, what's the context?


Since Wordpress default behaviour is to generate all the different image sizes, even for large images in media library, this may not be an expensive operation, especially as the avatars are not large, so I think we could do that.
However that's different from your current problem where you are wanting an override to display size.

**Comment by Jon007** [comment]
We could add some notes to the instructions to advise people if they want to change the avatar size.

eg:

Wordpress standard themes shows some quite small avatars by default, so you might want to increase the size now you have beautiful cat avatars, so here is how to do that:

**How to change  the author avatar size**
Look for the filter for your theme eg from twenty-fifteen:
```
$author_bio_avatar_size = apply_filters( 'twentyfifteen_author_bio_avatar_size', 56 );
echo get_avatar( get_the_author_meta( 'user_email' ), $author_bio_avatar_size );
```
if you have a child theme you can just copy author-bio.php and change number here from 56 to whatever you need, or do it the wordpress way and hook the filter twentyfifteen_author_bio_avatar_size.

**How to change the comment avatar size**
Again this depends on your theme but typically there is a comments.php which has a call to wp_list_comments();  so this can be changed to call eg:
```
wp_list_comments( array(
    'avatar_size' => 100
) );
```
or whatever your preferred size is

**Comment by Jon007** [comment]
Just to confirm: I added cat avatars to a standard wordpress and woocommerce site today without BuddyPress or Ultimate Member today, and I changed the avatar size ok without touching the cat avatar plugin.

**Comment by NoahDragon** [comment]
Okay. I got your idea. You are right, the best way to manage the avatar size is by theme. I'm on a wrong track. I think we could add the instruction message in the next release.
